package com.java.exception_handling;

import java.util.Scanner;

public class Main4 {

	public static void main(String[] args) {

//		catch{
//			
//		}

		try {// try finally

		} finally {

		}

		try (Scanner sc = new Scanner(System.in);) {// try with resource can exist alone

		}

	}

}
